name: Build
on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        target:
          - darwin-amd64
          - darwin-arm64
          - windows-amd64
          - windows-arm64
          - linux-amd64
          - linux-arm64
          - linux-loong64
          - linux-mips64
          - linux-mips64le
          - linux-ppc64
          - linux-ppc64le
          - linux-riscv64
          - linux-s390x
          - aix-ppc64
          - dragonfly-amd64
          - freebsd-amd64
          - freebsd-arm64
          - freebsd-riscv64
          - illumos-amd64
          - netbsd-amd64
          - netbsd-arm64
          - openbsd-amd64
          - openbsd-arm64
          - openbsd-ppc64
          - openbsd-riscv64
          - solaris-amd64
    name: Build
    runs-on: ${{ matrix.platform }}
    env:
      TARGET: ${{ matrix.target }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: gucooing/BaPs
        ref: "main"
        fetch-depth: 0

    - uses: benjlevesque/short-sha@v3.0
      id: short-sha

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23.2"
        check-latest: true

    - name: Build Proto
      run: |
          cd ./common/server_only
          chmod 777 ./protoc ./protoc-gen-go
          ./protoc --proto_path=. --plugin=protoc-gen-go=./protoc-gen-go --go_out=. *.proto

    - name: Sync Excel
      run: wget ${{ secrets.EXCEL_URL }} -O ./pkg/mx/excel.go

    - name: Build
      run: |
        TARGET_SPLIT=(${TARGET//-/ })
        GOOS=${TARGET_SPLIT[0]}
        GOARCH=${TARGET_SPLIT[1]}
        
        OUTPUT_NAME="BaPs_"$GOOS"_"$GOARCH
        if [ "$GOOS" = "windows" ]; then
          OUTPUT_NAME="$OUTPUT_NAME.exe"
        fi
        
        echo "Building for $GOOS-$GOARCH..."
        GOOS=$GOOS GOARCH=$GOARCH \
        go build -ldflags="-s -w" -o ./bin/$OUTPUT_NAME ./cmd/BaPs/BaPs.go

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: BaPs_${{ env.SHA }}_${{ matrix.target }}
        path: bin/*

    - name: Upload data
      uses: actions/upload-artifact@v4
      with:
        name: data.zip
        path: data/*