name: Docker BaPs

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
      R2_BUCKET: ${{ secrets.R2_BUCKET }}

    steps:
      - name: Sync BaPs
        uses: actions/checkout@v3
        with:
          repository: gucooing/BaPs
          ref: "main"
          fetch-depth: 0

      - name: github docker login
        run: echo ${{ secrets.TOKEN }} | docker login ghcr.io -u gucooing --password-stdin
#
#      - name: Build and push Docker image
#        run: |
#          docker buildx create --use --name multi-platform-builder --driver docker-container
#          docker run --rm --privileged tonistiigi/binfmt:latest --install all
#          docker buildx build \
#            --platform linux/amd64,linux/arm64 \
#            -t ghcr.io/gucooing/baps:latest \
#            --push \
#            Dockerfile .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          secrets: |
            R2_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }}
            R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }}
          build-args: |
            R2_ENDPOINT=${{ env.R2_ENDPOINT }}
            R2_BUCKET=${{ env.R2_BUCKET }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/gucooing/baps:latest